-- ~/.config/zenvim/lua/zen/plugins/ui.lua

return {
	{
		"mavantgarderc/prismpunk.nvim",
		lazy = false,
		priority = 900,

		config = function()
			require("prismpunk").setup({
				-- scheme = "kanagawa/paper/pebble",

				-- themes = {
				-- 	"kanagawa",
				-- 	"tmnt",
				-- 	"dc",
				-- 	-- "detox",
				-- 	-- "punk-cultures",
				-- 	"nvim-builtins",
				-- },

				styles = {
					comments = { italic = true },
					keywords = { bold = false },
					functions = { bold = true },
					variables = {},
				},

				overrides = {
					colors = {},
					highlights = {},
				},

				integrations = {
					cmp = true,
					telescope = true,
					gitsigns = true,
					lualine = true,
				},

				terminals = {
					enabled = true,
					emulator = { "alacritty", "ghostty" },
					ghostty = {
						enabled = true,
						auto_reload = true,
						config_path = vim.fn.expand("~/.config/ghostty/themes/prismpunk.toml"),
					},
					alacritty = {
						enabled = true,
						auto_reload = true,
						config_path = vim.fn.expand("~/.config/alacritty/prismpunk.toml"),
					},
				},
			})
		end,
	},

	{
		"nvim-tree/nvim-web-devicons",
		lazy = true,
	},

	-- {
	-- 	"nvim-lualine/lualine.nvim",
	-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
	-- 	config = function()
	-- 		require("lualine").setup({
	-- 			options = {
	-- 				theme = "auto",
	-- 				icons_enabled = true,
	-- 				component_separators = { left = "│", right = "│" },
	-- 				section_separators = { left = "", right = "" },
	-- 			},
	-- 		})
	-- 	end,
	-- },

	{
		"mavantgarderc/raphael.nvim",
		lazy = false,

		keys = {
			{
				"<leader>tp",
				function()
					require("raphael").open_picker({ only_configured = true })
				end,
				desc = "Raphael: Configured themes",
			},
			{
				"<leader>t/",
				function()
					require("raphael").open_picker({ exclude_configured = true })
				end,
				desc = "Raphael: All other themes",
			},
			{
				"<leader>ta",
				function()
					require("raphael").toggle_auto()
				end,
				desc = "Raphael: Toggle auto-apply",
			},
			{
				"<leader>tR",
				function()
					require("raphael").refresh_and_reload()
				end,
				desc = "Raphael: Refresh themes",
			},
			{
				"<leader>ts",
				function()
					require("raphael").show_status()
				end,
				desc = "Raphael: Show status",
			},
		},

		opts = {

			enable_picker = true,
			bookmark_group = true,
			recent_group = false,
			enable_autocmds = true,
			enable_commands = true,
			project_overrides_filetype = true,
			filetype_overrides_project = false,

			icons = {
				BOOKMARK = "[B]",
				CURRENT_ON = "=> ",
				CURRENT_OFF = " ",
				GROUP_EXPANDED = "[-]",
				GROUP_COLLAPSED = "[+]",
			},

			enable_keymaps = true,
			leader = "<leader>t",
			mappings = {
				picker = "p",
				next = ">",
				previous = "<",
				others = "/",
				auto = "a",
				refresh = "R",
				status = "s",
				random = "r",
			},

			profiles = {
				base = {},
				-- work = {
				-- default_theme = "kanagawa-paper-edo",
				-- },
				-- 	night = {
				-- 		default_theme = "detox-ink",
				-- 	},
				-- 	presentation = {
				-- 		default_theme = "kanagawa-paper-obsidian",
				-- 	},
			},
			-- current_profile = "work",

			sample_preview = {
				enabled = true,
				relative_size = 0.5,
				languages = {
					"lua",
					"python",
					"javascript",
					"rust",
					"go",
					"ruby",
					"sh",
					"sql",
				},
			},

			theme_aliases = {
				-- ["kanagawa-paper-sunset"] = "Kanagawa (Paper SUNSET)",
			},

			group_aliases = {
				emotional_entities = "Emotional Entities",
			},

			theme_map = {

				norse = {
					yggdrasill = {
						"norse-yggdrasill-askr",
						"norse-yggdrasill-nidhoggr",
						"norse-yggdrasill-ratatoskr",
						"norse-yggdrasill-vedrfolnir",
						"norse-yggdrasill-dainn",
						"norse-yggdrasill-dvalinn",
						"norse-yggdrasill-duneyrr",
						"norse-yggdrasill-duratror",
						"norse-yggdrasill-urdarbrunnr",
						"norse-yggdrasill-mimisbrunnr",
						"norse-yggdrasill-hvergelmir",
						"norse-yggdrasill-realm-alfheimr",
						"norse-yggdrasill-realm-asgardr",
						"norse-yggdrasill-realm-helheimr",
						"norse-yggdrasill-realm-jotunheimr",
						"norse-yggdrasill-realm-midgardr",
						"norse-yggdrasill-realm-muspelheimr",
						"norse-yggdrasill-realm-niflheimr",
						"norse-yggdrasill-realm-svartalfheimr",
						"norse-yggdrasill-realm-vanaheimr",
					},

					vanaheim = {
						"norse-vanaheim-freyr",
						"norse-vanaheim-freyja",
						"norse-vanaheim-njordr",
						"norse-vanaheim-gullveig",
						"norse-vanaheim-folkvangr",
						"norse-vanaheim-gullinbursti",
					},

					midgard = {
						"norse-midgard-jormungandr",
						"norse-midgard-sigurdr",
						"norse-midgard-starkadr",
						"norse-midgard-gramr",
						"norse-midgard-nornir",
						"norse-midgard-draugr",
					},

					jotunheim = {
						"norse-jotunheim-loki",
						"norse-jotunheim-sigyn",
						"norse-jotunheim-ymir",
						"norse-jotunheim-skadi",
						"norse-jotunheim-angrboda",
						"norse-jotunheim-thrymr",
						"norse-jotunheim-utgarda-loki",
						"norse-jotunheim-skrymir",
						"norse-jotunheim-hrungnir",
						"norse-jotunheim-thjazi",
						"norse-jotunheim-skoll",
						"norse-jotunheim-hati",
						"norse-jotunheim-fenrir",
						"norse-jotunheim-gleipnir",
					},

					helheim = {
						"norse-helheim-helheimr",
						"norse-helheim-hel",
						"norse-helheim-gramr",
						"norse-helheim-modgudr",
						"norse-helheim-gjallarbru",
					},

					niflheim = {
						"norse-niflheim-niflheimr",
						"norse-niflheim-elivagar",
						"norse-niflheim-naglfar",
						"norse-niflheim-audhumla",
					},

					muspelheim = {
						"norse-muspelheim-muspelheimr",
						"norse-muspelheim-surtr",
						"norse-muspelheim-surtalogi",
					},

					alfheim = {
						"norse-alfheim-alfheimr",
						"norse-alfheim-ljosalfar",
						"norse-alfheim-byggvir",
					},

					svartalfheim = {
						"norse-svartalfheim-svartalfheimr",
						"norse-svartalfheim-dvergar",
						"norse-svartalfheim-andvaranautr",
						"norse-svartalfheim-brisingamen",
						"norse-svartalfheim-tyrfingr",
						"norse-svartalfheim-brokkr",
						"norse-svartalfheim-eitri",
						"norse-svartalfheim-felnir",
						"norse-svartalfheim-alsvidr",
						"norse-svartalfheim-dvalinn",
					},

					asgard = {
						"norse-asgard-odinn",
						"norse-asgard-thorr",
						"norse-asgard-frigg",
						"norse-asgard-sif",
						"norse-asgard-baldr",
						"norse-asgard-tyr",
						"norse-asgard-heimdallr",
						"norse-asgard-idunn",
						"norse-asgard-bragi",
						"norse-asgard-vidarr",
						"norse-asgard-vali",
						"norse-asgard-ullr",
						"norse-asgard-hodr",
						"norse-asgard-magni",
						"norse-asgard-modi",
						"norse-asgard-valholl",
						"norse-asgard-bifrost",
						"norse-asgard-sleipnir",
						"norse-asgard-brynhildr",
						"norse-asgard-sigrdrifа",
						"norse-asgard-svafa",
						"norse-asgard-olrun",
						"norse-asgard-kara",
						"norse-asgard-mist",
						"norse-asgard-skogul",
						"norse-asgard-hlokk",
						"norse-asgard-mjollnir",
						"norse-asgard-gungnir",
						"norse-asgard-gjallarhorn",
						"norse-asgard-hringhorni",
						"norse-asgard-skidbladnir",
					},
				},

				dc = {
					arkham_asylum = {
						"arkham-asylum-amadeus-arkham",
						"arkham-asylum-black-mask",
						"arkham-asylum-calendarman",
						"arkham-asylum-captain-boomerang",
						"arkham-asylum-clayface",
						"arkham-asylum-deathshot",
						"arkham-asylum-firefly",
						"arkham-asylum-gypsy",
						"arkham-asylum-harley-quinn",
						"arkham-asylum-hush",
						"arkham-asylum-james-gordon-junior",
						"arkham-asylum-katana",
						"arkham-asylum-manbat",
						"arkham-asylum-neojoker",
						"arkham-asylum-poison-ivy",
						"arkham-asylum-prometheus",
						"arkham-asylum-riddler",
						"arkham-asylum-scarecrow",
						"arkham-asylum-sofia-falcone",
						"arkham-asylum-solomon-grundy",
						"arkham-asylum-vixen",
						"arkham-asylum-white-knight",
					},

					bat_family = {
						"bat-family-alfred-penyworth",
						"bat-family-azrael",
						"bat-family-batgirl",
						"bat-family-batman-beyond",
						"bat-family-batman-classic",
						"bat-family-batman1000000",
						"bat-family-batwoman",
						"bat-family-blackbat",
						"bat-family-bruce-wayne",
						"bat-family-catwoman",
						"bat-family-huntress",
						"bat-family-james-gordon",
						"bat-family-lucius-fox",
						"bat-family-nightwing",
						"bat-family-oracle",
						"bat-family-red-hood",
						"bat-family-red-robin",
						"bat-family-robin",
						"bat-family-selina-kyle",
					},

					crime_syndicate = {
						"crime-syndicate-black-siren",
						"crime-syndicate-deadeye",
						"crime-syndicate-deathstorm",
						"crime-syndicate-dr-chaos",
						"crime-syndicate-grid",
						"crime-syndicate-johnny-quick",
						"crime-syndicate-martian",
						"crime-syndicate-owlman",
						"crime-syndicate-power-ring",
						"crime-syndicate-sea-king",
						"crime-syndicate-superwoman",
						"crime-syndicate-ultraman",
					},

					emotional_entities = {
						"emotional-entities-adara",
						"emotional-entities-butcher",
						"emotional-entities-entity",
						"emotional-entities-ion",
						"emotional-entities-nekron",
						"emotional-entities-ophidian",
						"emotional-entities-parallax",
						"emotional-entities-predator",
						"emotional-entities-proselyte",
						"emotional-entities-relic",
						"emotional-entities-umbrax",
					},

					injustice_league = {
						"injustice-league-bizarro",
						"injustice-league-black-adam",
						"injustice-league-black-manta",
						"injustice-league-brainiac",
						"injustice-league-captain-cold",
						"injustice-league-cheetah",
						"injustice-league-deathstroke",
						"injustice-league-giganta",
						"injustice-league-gorilla-grod",
						"injustice-league-joker",
						"injustice-league-killer-frost",
						"injustice-league-killercroc",
						"injustice-league-lex-luthor",
						"injustice-league-mr-freeze",
						"injustice-league-mr-terrible",
						"injustice-league-multiman",
						"injustice-league-nocturna",
						"injustice-league-penguin",
						"injustice-league-sinestro",
						"injustice-league-twoface",
					},

					justice_league = {
						"justice-league-adam-strange",
						"justice-league-aquaman",
						"justice-league-batman",
						"justice-league-black-canary",
						"justice-league-blue-beetle",
						"justice-league-booster-gold",
						"justice-league-captain-atom",
						"justice-league-constantine",
						"justice-league-cyborg",
						"justice-league-dr-fate",
						"justice-league-etrigan",
						"justice-league-firestorm",
						"justice-league-flash",
						"justice-league-green-arrow",
						"justice-league-green-lantern-guy-gardner",
						"justice-league-green-lantern-hal-jordan",
						"justice-league-green-lantern-jessica-cruz",
						"justice-league-green-lantern-john-stewart",
						"justice-league-green-lantern-kyle-rayner",
						"justice-league-hawkgirl",
						"justice-league-hawkman",
						"justice-league-lobo",
						"justice-league-martian-manhunter",
						"justice-league-mera",
						"justice-league-mr-terrific",
						"justice-league-raven",
						"justice-league-red-tornado",
						"justice-league-shazam",
						"justice-league-spectre",
						"justice-league-starfire",
						"justice-league-superman",
						"justice-league-wonder-woman",
						"justice-league-zatanna",
					},

					lanter_corps = {
						"lantern-corps-black",
						"lantern-corps-blue",
						"lantern-corps-gold",
						"lantern-corps-green",
						"lantern-corps-indigo",
						"lantern-corps-orange",
						"lantern-corps-phantom-balanced",
						"lantern-corps-phantom-chaos",
						"lantern-corps-phantom-corrupted",
						"lantern-corps-red",
						"lantern-corps-ultraviolet-spectral",
						"lantern-corps-ultraviolet-veiled",
						"lantern-corps-violet",
						"lantern-corps-white",
						"lantern-corps-yellow",
					},

					league_of_assassins = {
						"league-of-assassins-athanasia",
						"league-of-assassins-bane",
						"league-of-assassins-black-spider",
						"league-of-assassins-blank",
						"league-of-assassins-lady-shiva",
						"league-of-assassins-nyssa-raatko",
						"league-of-assassins-ras-al-ghul",
						"league-of-assassins-talia",
					},

					new_gods = {
						apokolips = {
							"apokolips-darkseid",
							"apokolips-desaad",
							"apokolips-grayven",
							"apokolips-heggra",
							"apokolips-kalibak",
							"apokolips-pythia",
							"apokolips-yugakhan",
						},
						new_genesis = {
							"new-genesis-big-barda",
							"new-genesis-highfather",
							"new-genesis-lightray",
							"new-genesis-metron",
							"new-genesis-mister-miracle",
							"new-genesis-orion",
							"new-genesis-takion",
						},
					},

					super_family = {
						"super-family-clark-kent",
						"super-family-composite-superman",
						"super-family-conner-kent",
						"super-family-dreamer",
						"super-family-eradicator",
						"super-family-jonathan-kent",
						"super-family-lois-lane",
						"super-family-lucy-lane",
						"super-family-martha-kent",
						"super-family-steel",
						"super-family-supergirl",
						"super-family-superman-classic",
						"super-family-superman-kingdomcome",
						"super-family-superman-modern",
					},

					watchmen = {
						"watchmen-dr-manhattan",
						"watchmen-nite-owl",
						"watchmen-ozymandias",
						"watchmen-rorschach",
						"watchmen-silk-spectre",
						"watchmen-the-comedian",
					},
				},

				kanagawa = {
					kami = {
						"kanagawa-kami-storm",
						"kanagawa-kami-crimsonnight",
						"kanagawa-kami-eclipse",
						"kanagawa-kami-obsidian",
						"kanagawa-kami-fujin",
						"kanagawa-kami-raijin",
						"kanagawa-kami-tsukuyomi",
						"kanagawa-kami-inari",
						"kanagawa-kami-benzaiten",
					},
					paper = {
						"kanagawa-paper-dawn",
						"kanagawa-paper-dragon",
						"kanagawa-paper-edo",
						"kanagawa-paper-nightfall",
						"kanagawa-paper-sunset",
						"kanagawa-paper-crimson",
						"kanagawa-paper-floral",
						"kanagawa-paper-azure",
						"kanagawa-paper-wave",
						"kanagawa-paper-katana",
						"kanagawa-paper-ronin",
						"kanagawa-paper-frost",
						"kanagawa-paper-canopy",
						"kanagawa-paper-ember",
						"kanagawa-paper-moss",
						"kanagawa-paper-pebble",
						"kanagawa-paper-claysoil",
						"kanagawa-paper-permafrost",
						"kanagawa-paper-tideline",
						"kanagawa-paper-bamboo",
						"kanagawa-paper-cinder",
						"kanagawa-paper-lichen",
						"kanagawa-paper-torrential",
						"kanagawa-paper-undergrowth",
						"kanagawa-paper-lacquer",
						"kanagawa-paper-indigo",
						"kanagawa-paper-shrinegate",
						"kanagawa-paper-woodblock",
						"kanagawa-paper-ironfan",
						"kanagawa-paper-haiku",
						"kanagawa-paper-rakuichi",
						"kanagawa-paper-woodgrain",
						"kanagawa-paper-wavecrest",
						"kanagawa-paper-ukiyo",
					},
					zen = {
						"kanagawa-zen-tokonoma",
						"kanagawa-zen-tatami",
						"kanagawa-zen-stonegarden",
						"kanagawa-zen-dojo",
						"kanagawa-zen-inkstone",
						"kanagawa-zen-brushstroke",
						"kanagawa-zen-void",
						"kanagawa-zen-blackscroll",
						"kanagawa-zen-liminal",
						"kanagawa-zen-silence",
						"kanagawa-zen-dissolution",
					},
				},

				punk = {
					"acidpunk",
					"aquapunk",
					"atompunk",
					"biopunk",
					"clockpunk",
					"cryopunk",
					"cyberpunk",
					"decopunk",
					"dieselpunk",
					"duskpunk",
					"gothicpunk",
					"junglepunk",
					"junkpunk",
					"nanopunk",
					"solarpunk",
					"splatterpunk",
					"steampunk",
					"stonepunk",
					"techpunk",
				},

				tmnt = {
					"tmnt-april-oneal",
					"tmnt-casey-jones",
					"tmnt-donatello",
					"tmnt-last-ronin",
					"tmnt-leonardo",
					"tmnt-michelangelo",
					"tmnt-raphael",
					"tmnt-shredder",
					"tmnt-splinter",
				},

				-- detox = {
				-- 	"detox-1998term",
				-- 	"detox-ash",
				-- 	"detox-bone",
				-- 	"detox-bunker",
				-- 	"detox-clay",
				-- 	"detox-coal",
				-- 	"detox-concrete",
				-- 	"detox-copper",
				-- 	"detox-dust",
				-- 	"detox-ember",
				-- 	"detox-fog",
				-- 	"detox-frost",
				-- 	"detox-glass",
				-- 	"detox-ink",
				-- 	"detox-iron",
				-- 	"detox-jade",
				-- 	"detox-linen",
				-- 	"detox-mercury",
				-- 	"detox-moss",
				-- 	"detox-moth",
				-- 	"detox-mute",
				-- 	"detox-paper",
				-- 	"detox-petal",
				-- 	"detox-plaster",
				-- 	"detox-prison",
				-- 	"detox-rain",
				-- 	"detox-rust",
				-- 	"detox-scar",
				-- 	"detox-sepia",
				-- 	"detox-shadow",
				-- 	"detox-silk",
				-- 	"detox-silt",
				-- 	"detox-slate",
				-- 	"detox-smoke",
				-- 	"detox-sterile",
				-- 	"detox-stone",
				-- 	"detox-void",
				-- 	"detox-wool",
				-- 	"detox-zenkanagawa",
				-- 	"detox-zenpaper",
				-- },

				nvim_builtins = {
					"prism-habamax",
					"prism-quiet",
					"prism-retrobox",
					"prism-slate",
					"prism-sorbet",
				},
			},

			filetype_themes = {
				alpha = "kanagawa-paper-edo",
				netrw = "kanagawa-paper-edo",
				minifiles = "kanagawa-paper-edo",
				lazy = "kanagawa-paper-edo",
				help = "kanagawa-paper-edo",
				lua = "kanagawa-paper-edo",
				mason = "kanagawa-paper-edo",
				tmux = "kanagawa-paper-edo",
				oil = "kanagawa-paper-edo",
				kdl = "kanagawa-paper-edo",
				toml = "kanagawa-paper-edo",
				conf = "kanagawa-paper-edo",
				sh = "kanagawa-paper-edo",
				zsh = "kanagawa-paper-edo",
				hyprlang = "kanagawa-paper-edo",
				csv = "kanagawa-paper-edo",
				md = "base16-catppuccin-frappe",
				tex = "base16-catppuccin-mocha",
				-- cs = "gruvbox",
				cs = "base16-gruvbox-dark-hard",
				csx = "base16-gruvbox-dark-hard",
				csproj = "base16-gruvbox-dark-pale",
				xml = "base16-gruvbox-dark-pale",
				solution = "base16-gruvbox-material-dark-hard",
				python = "kanagawa-paper-sunset",
				solidity = "base16-darkmoss",
				sql = "kanagawa-paper-dragon",
				sqls = "kanagawa-paper-dragon",
				html = "tokyonight",
				css = "tokyonight",
				javascript = "nordfox",
				typescript = "duskfox",
				json = "base16-rose-pine",
				jsonc = "base16-rose-pine",
			},

			project_themes = {},
		},
	},
}
