return {
	{
		dir = "~/projects/0-shelfs/CodeStorage/nvim-plugins/prismpunk.nvim",
		name = "prismpunk.nvim",
		lazy = false,
		priority = 900,
		config = function()
			require("prismpunk").setup({
				styles = {
					comments = { italic = true },
					keywords = { bold = false },
					functions = { bold = true },
					variables = {},
				},
				overrides = {
					colors = {},
					highlights = {},
				},
				integrations = {
					cmp = true,
					telescope = true,
					gitsigns = true,
					lualine = true,
				},
				terminals = {
					enabled = true,
					emulator = { "alacritty", "ghostty" },
					ghostty = {
						enabled = true,
						auto_reload = true,
						config_path = vim.fn.expand("~/.config/ghostty/themes/prismpunk.toml"),
					},
					alacritty = {
						enabled = true,
						auto_reload = true,
						config_path = vim.fn.expand("~/.config/alacritty/prismpunk.toml"),
					},
				},
			})
		end,
	},

	{
		"nvim-tree/nvim-web-devicons",
		lazy = true,
	},

	{
		"mavantgarderc/raphael.nvim",
		event = "UIEnter",
		opts = {
			default_theme = "kanagawa-paper-crimson",
			enable_picker = true,
			bookmark_group = true,
			recent_group = false,
			enable_autocmds = true,
			enable_commands = true,
			project_overrides_filetype = true,
			filetype_overrides_project = false,
			icons = {
				BOOKMARK = "[B]",
				CURRENT_ON = "=> ",
				CURRENT_OFF = " ",
				GROUP_EXPANDED = "[-]",
				GROUP_COLLAPSED = "[+]",
			},
			-- enable_keymaps = true,
			-- leader = "<leader>t",
			-- mappings = {
			-- 	picker = "p",
			-- 	next = ">",
			-- 	previous = "<",
			-- 	others = "/",
			-- 	auto = "a",
			-- 	refresh = "R",
			-- 	status = "s",
			-- 	random = "r",
			-- },

			profiles = {
				base = {},
				-- work = {
				-- default_theme = "kanagawa-paper-edo",
				-- },
				-- 	night = {
				-- 		default_theme = "detox-ink",
				-- 	},
				-- 	presentation = {
				-- 		default_theme = "kanagawa-paper-obsidian",
				-- 	},
			},
			-- current_profile = "work",
			sample_preview = {
				enabled = true,
				relative_size = 0.5,
				languages = {
					"lua",
					"python",
					"javascript",
					"rust",
					"go",
					"ruby",
					"sh",
					"sql",
				},
			},
			-- theme_aliases = { ["kanagawa-paper-sunset"] = "Kanagawa (Paper SUNSET)", },
			group_aliases = {
				emotional_entities = "Emotional Entities",
			},

			theme_map = {
				norse = {
					"norse-yggdrasill-ratatoskr",
					"norse-yggdrasill-askr",
					"norse-yggdrasill-dainn",
					"norse-yggdrasill-realm-asgardr",
					"norse-yggdrasill-realm-midgardr",
					"norse-yggdrasill-realm-vanaheimr",
					"norse-vanaheim-folkvangr",
					"norse-vanaheim-freyr",
					"norse-vanaheim-njordr",
					"norse-midgard-gramr",
					"norse-midgard-nornir",
					"norse-midgard-starkadr",
					"norse-jotunheim-skadi",
					"norse-jotunheim-sigyn",
					"norse-jotunheim-ymir",
					"norse-helheim-hel",
					"norse-niflheim-naglfar",
					"norse-svartalfheim-dvergar",
					"norse-asgard-bifrost",
					"norse-asgard-heimdallr",
					"norse-asgard-hlokk",
					"norse-asgard-hodr",
					"norse-asgard-mist",
					"norse-asgard-olrun",
					"norse-asgard-odinn",
					"norse-asgard-svafa",
					"norse-asgard-vidarr",
					"norse-asgard-sleipnir",
				},
				kanagawa = {
					"kanagawa-kami-crimsonnight",
					"kanagawa-kami-eclipse",
					"kanagawa-kami-fujin",
					"kanagawa-kami-obsidian",
					"kanagawa-kami-storm",
					"kanagawa-paper-azure",
					"kanagawa-paper-canopy",
					"kanagawa-paper-crimson",
					"kanagawa-paper-cinder",
					"kanagawa-paper-dragon",
					"kanagawa-paper-edo",
					"kanagawa-paper-floral",
					"kanagawa-paper-nightfall",
					"kanagawa-paper-katana",
					"kanagawa-paper-moss",
					"kanagawa-paper-pebble",
					"kanagawa-paper-ronin",
					"kanagawa-paper-sunset",
					"kanagawa-zen-void",
					"kanagawa-zen-liminal",
					"kanagawa-zen-silence",
					"kanagawa-zen-brushstroke",
					"kanagawa-zen-dissolution",
				},

				comic = {
					"tmnt-last-ronin",
					"tmnt-shredder",
					"tmnt-splinter",
					"arkham-asylum-amadeus-arkham",
					"arkham-asylum-hush",
					"arkham-asylum-sofia-falcone",
					"arkham-asylum-solomon-grundy",
					"bat-family-bruce-wayne",
					"bat-family-selina-kyle",
					"crime-syndicate-deathstorm",
					"crime-syndicate-owlman",
					"crime-syndicate-sea-king",
					"emotional-entities-entity",
					"emotional-entities-relic",
					"injustice-league-brainiac",
					"injustice-league-deathstroke",
					"injustice-league-killercroc",
					"injustice-league-twoface",
					"justice-league-blue-beetle",
					"justice-league-superman",
					"justice-league-wonder-woman",
					"justice-league-spectre",
					"justice-league-red-tornado",
					"super-family-superman-kingdomcome",
					"super-family-martha-kent",
					"super-family-clark-kent",
					"super-family-jonathan-kent",
					"watchmen-ozymandias",
				},
			},
			-- filetype_themes = { netrw = "kanagawa-paper-edo", },
			-- project_themes = {},
		},
	},

	{
		"mcauley-penney/visual-whitespace.nvim",
		event = "ModeChanged *:[vV\22]",
		opts = {
			enabled = true,
			highlight = { link = "Visual", default = true },
			match_types = {
				space = true,
				tab = true,
				nbsp = true,
				lead = false,
				trail = false,
			},
			list_chars = {
				space = "·",
				tab = "↦",
				nbsp = "␣",
				lead = "‹",
				trail = "›",
			},
			fileformat_chars = {
				unix = "↲",
				mac = "←",
				dos = "↙",
			},
			ignore = { filetypes = {}, buftypes = {} },
		},
	},
}
